# Generated by Django 2.1.3 on 2019-02-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=250)),
                ('avatar', models.ImageField(upload_to='')),
                ('campus', models.CharField(choices=[('Msc', 'Moscow'), ('Spb', 'Saint-Petersburg'), ('NNvgd', 'Nizhny Novgorod'), ('Perm', 'Perm')], max_length=100)),
            ],
        ),
    ]
